### ISSUE TITLE
[Feature] Support Whisper large-v3

### ISSUE THREAD

**Issue by RayBB** [pluja/whishper#48]
**Description of the feature you are requesting:**
Support the latest version of whisper https://news.ycombinator.com/item?id=38166965

**Describe the solution you'd like**
Be able to select it like the other models

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Arche151** [comment]
So, faster-whisper - the implementation of Whisper, that Whishper is utilizing - is not capable of using large-v3 yet. So we need to wait for that to happen. 

There is already an issue about it https://github.com/guillaumekln/faster-whisper/issues/544 but I'm not sure if faster-whisper will migrate to large-v3 since its brilliant developer Guillaume Klein started a job as Machine Learning Engineer at Apple last month.

**Comment by pluja** [comment]
Keep an eye on this PR: https://github.com/guillaumekln/faster-whisper/pull/548

When merged, I will update to support it.

**Comment by thibaultmol** [comment]
so https://github.com/SYSTRAN/faster-whisper/pull/578 got merged instead.
So v3 is going to be added to whishper soon then?

**Comment by pluja** [comment]
Added in 82b531fa45dfa6509232a62ac16856247823fe34

**Comment by pluja** [comment]
Now available in [v3.1.0](https://github.com/pluja/whishper/releases/tag/v3.1.0)
